# Generated by Django 4.2.16 on 2025-07-23 22:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycontact',
            name='city',
            field=models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator(message='City can only contain letters, spaces, hyphens, and periods', regex='^[a-zA-Z\\s\\-\\.]+$')]),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='first_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name can only contain letters, spaces, hyphens, apostrophes, and periods', regex="^[a-zA-Z\\s\\-\\'\\.]+$"), django.core.validators.MinLengthValidator(1, message='First name is required')]),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='last_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name can only contain letters, spaces, hyphens, apostrophes, and periods', regex="^[a-zA-Z\\s\\-\\'\\.]+$"), django.core.validators.MinLengthValidator(1, message='Last name is required')]),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='phone_primary',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (e.g., (555) 123-4567 or 555-123-4567)', regex='^\\+?1?[-.\\s]?\\(?[0-9]{3}\\)?[-.\\s]?[0-9]{3}[-.\\s]?[0-9]{4}$')]),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='phone_secondary',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (e.g., (555) 123-4567 or 555-123-4567)', regex='^\\+?1?[-.\\s]?\\(?[0-9]{3}\\)?[-.\\s]?[0-9]{3}[-.\\s]?[0-9]{4}$')]),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='state',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator(message='State can only contain letters and spaces', regex='^[a-zA-Z\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='street',
            field=models.CharField(blank=True, max_length=200, validators=[django.core.validators.RegexValidator(message='Street address can only contain letters, numbers, spaces, hyphens, periods, commas, and #', regex='^[a-zA-Z0-9\\s\\-\\.\\,\\#]+$')]),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid ZIP code (e.g., 12345 or 12345-6789)', regex='^\\d{5}(-\\d{4})?$')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name can only contain letters, spaces, hyphens, apostrophes, and periods', regex="^[a-zA-Z\\s\\-\\'\\.]+$"), django.core.validators.MinLengthValidator(1, message='First name is required')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name can only contain letters, spaces, hyphens, apostrophes, and periods', regex="^[a-zA-Z\\s\\-\\'\\.]+$"), django.core.validators.MinLengthValidator(1, message='Last name is required')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator(message='Name can only contain letters, spaces, hyphens, apostrophes, and periods', regex="^[a-zA-Z\\s\\-\\'\\.]*$")]),
        ),
        migrations.AlterField(
            model_name='student',
            name='preferred_name',
            field=models.CharField(blank=True, help_text='Name student prefers to be called', max_length=100, validators=[django.core.validators.RegexValidator(message='Name can only contain letters, spaces, hyphens, apostrophes, and periods', regex="^[a-zA-Z\\s\\-\\'\\.]*$")]),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(blank=True, help_text='School-specific student ID number', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Student ID can only contain letters, numbers, and hyphens', regex='^[A-Za-z0-9\\-]+$')]),
        ),
    ]
