# Generated by Django 4.2.16 on 2025-07-22 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=255, unique=True)),
                ('search_count', models.IntegerField(default=1)),
                ('category', models.CharField(choices=[('student_name', 'Student Name'), ('course_name', 'Course Name'), ('teacher_name', 'Teacher Name'), ('subject', 'Subject'), ('grade_level', 'Grade Level'), ('general', 'General')], default='general', max_length=50)),
                ('last_searched', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-search_count', '-last_searched'],
                'indexes': [models.Index(fields=['term'], name='search_sear_term_d8480d_idx'), models.Index(fields=['category', '-search_count'], name='search_sear_categor_57def1_idx')],
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255)),
                ('search_type', models.CharField(choices=[('global', 'Global Search'), ('students', 'Students'), ('courses', 'Courses'), ('teachers', 'Teachers'), ('grades', 'Grades'), ('assignments', 'Assignments')], default='global', max_length=50)),
                ('filters_applied', models.JSONField(blank=True, default=dict)),
                ('results_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Search histories',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='search_sear_user_id_71e095_idx'), models.Index(fields=['query'], name='search_sear_query_d8a8e0_idx')],
            },
        ),
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('query', models.CharField(max_length=255)),
                ('search_type', models.CharField(choices=[('global', 'Global Search'), ('students', 'Students'), ('courses', 'Courses'), ('teachers', 'Teachers'), ('grades', 'Grades'), ('assignments', 'Assignments')], default='global', max_length=50)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_used'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
