# Generated by Django 4.2.16 on 2025-07-24 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_emergencycontact_city_and_more'),
        ('academics', '0002_absencereason_curriculumstandard_studentsubmission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='parent_message',
            field=models.ForeignKey(blank=True, help_text='The message this is replying to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='academics.message'),
        ),
        migrations.AddField(
            model_name='message',
            name='student_context',
            field=models.ForeignKey(blank=True, help_text='Student this message is about (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.student'),
        ),
        migrations.AddField(
            model_name='message',
            name='thread_id',
            field=models.CharField(blank=True, help_text='Messages with same thread_id are part of the same conversation', max_length=50),
        ),
    ]
