# Generated by Django 4.2.16 on 2025-07-24 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0003_student_family_access_users_parentverificationcode'),
        ('academics', '0003_message_parent_message_message_student_context_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarlyDismissalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField()),
                ('dismissal_time', models.TimeField()),
                ('reason', models.TextField()),
                ('pickup_person', models.CharField(help_text='Name of person picking up student', max_length=100)),
                ('contact_phone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('school_notes', models.TextField(blank=True)),
                ('actual_dismissal_time', models.TimeField(blank=True, null=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurring_days', models.CharField(blank=True, help_text='Comma-separated days: MON,TUE,WED,THU,FRI', max_length=20)),
                ('recurring_end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_dismissals', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dismissal_requests', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dismissal_requests', to='students.student')),
            ],
            options={
                'ordering': ['-request_date', '-dismissal_time'],
            },
        ),
    ]
