# Generated by Django 4.2.16 on 2025-07-24 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_family_access_users_parentverificationcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0004_earlydismissalrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('absence', 'Absence Alert'), ('tardiness', 'Tardiness Alert'), ('pattern', 'Pattern Alert'), ('early_dismissal', 'Early Dismissal Confirmation')], max_length=20)),
                ('message', models.TextField()),
                ('delivery_method', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('both', 'Email & SMS')], default='email', max_length=10)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('sms_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendance_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='academics.attendance')),
                ('dismissal_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='academics.earlydismissalrequest')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_notifications', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
