# Generated by Django 4.2.16 on 2025-07-24 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0003_student_family_access_users_parentverificationcode'),
        ('academics', '0005_attendancenotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolCalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(choices=[('holiday', 'Holiday'), ('early_dismissal', 'Early Dismissal'), ('no_school', 'No School'), ('half_day', 'Half Day'), ('testing', 'Testing Day'), ('conference', 'Parent-Teacher Conference'), ('event', 'School Event'), ('break', 'School Break')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, help_text='For events with specific times', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='For events with specific times', null=True)),
                ('dismissal_time', models.TimeField(blank=True, help_text='Early dismissal time', null=True)),
                ('is_public', models.BooleanField(default=True, help_text='Show to parents in portal')),
                ('color', models.CharField(default='#007bff', help_text='Hex color code for calendar display', max_length=7)),
                ('affects_all_students', models.BooleanField(default=True)),
                ('specific_grades', models.CharField(blank=True, help_text='Comma-separated grade levels if not affecting all (e.g., K,1,2)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='students.schoolyear')),
            ],
            options={
                'verbose_name': 'School Calendar Event',
                'verbose_name_plural': 'School Calendar Events',
                'ordering': ['start_date', 'start_time'],
            },
        ),
    ]
