# Generated by Django 4.2.16 on 2025-07-24 22:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0004_medicalinformation_authorizedpickupperson'),
        ('academics', '0007_messageattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration_minutes', models.IntegerField(default=15)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('CANCELLED', 'Cancelled')], default='AVAILABLE', max_length=20)),
                ('location', models.CharField(default='Classroom', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('booking_date', models.DateTimeField(blank=True, null=True)),
                ('parent_notes', models.TextField(blank=True, help_text='Notes from parent about conference topic')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_conferences', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conference_slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'unique_together': {('teacher', 'date', 'start_time')},
            },
        ),
    ]
