# Generated by Django 4.2.16 on 2025-07-25 00:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_medicalinformation_authorizedpickupperson'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0008_conferenceslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('document_type', models.CharField(choices=[('MEDICAL', 'Medical Document'), ('HOMEWORK', 'Homework/Assignment'), ('PERMISSION', 'Permission Slip'), ('PHOTO', 'Photo'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('file', models.FileField(upload_to='parent_uploads/%Y/%m/')),
                ('file_size', models.IntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('is_private', models.BooleanField(default=False, help_text='Only viewable by parent and admin')),
                ('shared_with_teachers', models.BooleanField(default=True)),
                ('shared_with_nurse', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/%Y/%m/')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='students.student')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
