# Generated by Django 4.2.16 on 2025-07-25 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0009_documentupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancenotification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_notifications_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='conferenceslot',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_conference_slots', to=settings.AUTH_USER_MODEL),
        ),
    ]
