# Generated by Django 4.2.16 on 2025-07-22 21:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schooldriver_modern", "0002_securityevent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="email_notifications",
            field=models.BooleanField(default=True, verbose_name="Email Notifications"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="emergency_address",
            field=models.TextField(
                blank=True, verbose_name="Emergency Contact Address"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="emergency_contact_1_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Primary Contact Name"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="emergency_contact_1_phone",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Primary Contact Phone"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="emergency_contact_1_relationship",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Primary Contact Relationship"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="emergency_contact_2_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Secondary Contact Name"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="emergency_contact_2_phone",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Secondary Contact Phone"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="emergency_contact_2_relationship",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Secondary Contact Relationship"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="parent_portal_access",
            field=models.BooleanField(
                default=True, verbose_name="Parent Portal Access"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="sms_notifications",
            field=models.BooleanField(default=False, verbose_name="SMS Notifications"),
        ),
    ]
