# Generated by Django 4.2.16 on 2025-07-24 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooldriver_modern', '0003_userprofile_address_userprofile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French')], default='en', max_length=10, verbose_name='Preferred Language'),
        ),
    ]
