# Generated by Django 4.2.16 on 2025-07-24 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schooldriver_modern', '0004_userprofile_preferred_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_notifications_email', models.BooleanField(default=True)),
                ('grade_notifications_sms', models.BooleanField(default=False)),
                ('grade_frequency', models.CharField(choices=[('IMMEDIATE', 'Immediate'), ('DAILY', 'Daily Summary'), ('WEEKLY', 'Weekly Summary'), ('OFF', 'Disabled')], default='IMMEDIATE', max_length=20)),
                ('attendance_notifications_email', models.BooleanField(default=True)),
                ('attendance_notifications_sms', models.BooleanField(default=True)),
                ('attendance_frequency', models.CharField(choices=[('IMMEDIATE', 'Immediate'), ('DAILY', 'Daily Summary'), ('WEEKLY', 'Weekly Summary'), ('OFF', 'Disabled')], default='IMMEDIATE', max_length=20)),
                ('assignment_reminders_email', models.BooleanField(default=True)),
                ('assignment_reminders_sms', models.BooleanField(default=False)),
                ('assignment_frequency', models.CharField(choices=[('IMMEDIATE', 'Immediate'), ('DAILY', 'Daily Summary'), ('WEEKLY', 'Weekly Summary'), ('OFF', 'Disabled')], default='DAILY', max_length=20)),
                ('announcement_notifications_email', models.BooleanField(default=True)),
                ('announcement_notifications_sms', models.BooleanField(default=False)),
                ('announcement_frequency', models.CharField(choices=[('IMMEDIATE', 'Immediate'), ('DAILY', 'Daily Summary'), ('WEEKLY', 'Weekly Summary'), ('OFF', 'Disabled')], default='IMMEDIATE', max_length=20)),
                ('emergency_notifications_email', models.BooleanField(default=True)),
                ('emergency_notifications_sms', models.BooleanField(default=True)),
                ('emergency_frequency', models.CharField(choices=[('IMMEDIATE', 'Immediate'), ('DAILY', 'Daily Summary'), ('WEEKLY', 'Weekly Summary'), ('OFF', 'Disabled')], default='IMMEDIATE', max_length=20)),
                ('conference_reminders_email', models.BooleanField(default=True)),
                ('conference_reminders_sms', models.BooleanField(default=False)),
                ('digest_time', models.TimeField(default='08:00:00', help_text='Time to send daily/weekly digests')),
                ('weekend_notifications', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preferences',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
    ]
